// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cleanCpp
Rcpp::DataFrame cleanCpp(std::vector<std::string> str);
RcppExport SEXP boostTest_cleanCpp(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type str(strSEXP);
    __result = Rcpp::wrap(cleanCpp(str));
    return __result;
END_RCPP
}
